[build]
target = "x86_64-pc-windows-msvc"

[alias]
# Aliases for Windows host
# xbuild = "build --release"
# xcheck = "check --release"
# xclippy = "clippy"
# xtest = "test --no-run"

# Aliases for Linux/macOS host (cross-compiling using cargo-xwin)
xbuild = "xwin build"
xcheck = "xwin check --release"
xclippy = "xwin clippy"
xtest = "xwin test --no-run"

# Aliases for Android target
abuild = "build --target aarch64-linux-android"
acheck = "check --target aarch64-linux-android --release"
aclippy = "clippy --target aarch64-linux-android"
atest = "test --target aarch64-linux-android --no-run"

[target.aarch64-linux-android]
# Windows host
# linker = "ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd"

# Linux host
linker = "ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"

rustflags = [
    "-C", "target-cpu=generic",
    "-C", "link-args=-lc++abi",
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=65536"
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=x86-64-v2"
]

[env]
# Note: Requires a symbolic link named 'ndk' in the project root pointing to your Android NDK.
# Example: ln -s /path/to/android-ndk-r27d ndk
# Windows host
# CC_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd", relative = true }
# CXX_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang++.cmd", relative = true }
# AR_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe", relative = true }
# BINDGEN_EXTRA_CLANG_ARGS = { value = "--sysroot=ndk/toolchains/llvm/prebuilt/windows-x86_64/sysroot", relative = true }
# CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = { value = "ndk/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd", relative = true }

# Linux host
CC_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang", relative = true }
CXX_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++", relative = true }
AR_aarch64_linux_android = { value = "ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar", relative = true }
BINDGEN_EXTRA_CLANG_ARGS = { value = "--sysroot=ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot", relative = true }
CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER = { value = "ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang", relative = true }
