name: Create Release

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on: workflow_dispatch

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v7
      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2

      - name: Grant execute permission to build scripts
        run: chmod +x tools/android/*.sh tools/windows/*.sh
      - uses: dtolnay/rust-toolchain@stable
      - name: Build Hachimi for Android
        run: |
          rustup target add aarch64-linux-android
          RELEASE=1 ./tools/android/build.sh
        env:
          HACHIMI_IGNORE_DIRTY: "true"

      - name: Attest Android
        uses: actions/attest@v4
        with:
          subject-path: |
            build/*.so
            build/sha256.json

      - name: Upload Android binaries
        uses: actions/upload-artifact@v7
        with:
          name: android
          path: |
            build/*.so
            build/sha256.json

  build-zygisk:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v7
      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2

      - name: Grant execute permission to build scripts
        run: chmod +x tools/android/*.sh tools/windows/*.sh
      - uses: dtolnay/rust-toolchain@stable
      - name: Build Hachimi Zygisk Module
        run: |
          rustup target add aarch64-linux-android
          RELEASE=1 ./tools/android/build_zygisk.sh
        env:
          HACHIMI_IGNORE_DIRTY: "true"

      - name: Attest Zygisk Module
        uses: actions/attest@v4
        with:
          subject-path: |
            build/zygisk-*.zip

      - name: Upload Zygisk Module
        uses: actions/upload-artifact@v7
        with:
          name: zygisk
          path: |
            build/zygisk-*.zip

  build-windows:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v7
      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2


      - uses: dtolnay/rust-toolchain@stable
      - name: Build Hachimi for Windows
        run: |
          bash tools/windows/build.sh
        env:
          HACHIMI_IGNORE_DIRTY: "true"
          RELEASE: "1"

      - name: Build Cellar
        run: |
          git clone --depth 1 --revision d4c3f79801c8131e26df585766c35e5ce11ec57f https://github.com/Hachimi-Hachimi/Cellar
          cd Cellar
          cargo build --target x86_64-pc-windows-msvc --target-dir build --release
          move build\x86_64-pc-windows-msvc\release\cellar.dll build
          cd ..

      - name: Check out FunnyHoney
        run: git clone --depth 1 --revision 418b5348bd9b7376cc7485c591ca69d49aa4d805 https://gitlab.com/LeadRDRK/FunnyHoney.git

      - name: Build Installer
        run: |
          git clone --depth 1 --revision b236ce341477890be1ee759bed8fd27c45862d7f https://github.com/teiosteppa/Installer
          copy build\hachimi.dll Installer
          move Cellar\build\cellar.dll Installer
          move FunnyHoney\FunnyHoney.exe Installer
          cd Installer
          cargo build --target x86_64-pc-windows-msvc --target-dir build --release --features compress_bin
          cd ..
          move Installer\build\x86_64-pc-windows-msvc\release\hachimi_installer.exe build

      - name: Get checksums for Windows binaries
        shell: bash
        run: |
          curl -L "https://github.com/BLAKE3-team/BLAKE3/releases/latest/download/b3sum_windows_x64_bin.exe" -o b3sum.exe
          DLL_HASH=($(./b3sum.exe build/hachimi.dll | tr -d '\r'))
          EXE_HASH=($(./b3sum.exe build/hachimi_installer.exe | tr -d '\r'))
          cat <<EOF > build/blake3.json
          {
            "hachimi.dll": "$DLL_HASH",
            "hachimi_installer.exe": "$EXE_HASH"
          }
          EOF

      - name: Attest Windows
        uses: actions/attest@v4
        with:
          subject-path: |
            build/blake3.json
            build/hachimi.dll
            build/hachimi_installer.exe

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: |
            build/blake3.json
            build/hachimi.dll
            build/hachimi_installer.exe

  create-release:
    needs: [build-android, build-zygisk, build-windows]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Get release version
        id: get_info
        run: |
          VERSION=$(awk '/^\[package\]/{flag=1} flag && /^version/{print $3; exit}' Cargo.toml | tr -d '"')
          echo "RELEASE_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Destroy existing release and tag
        run: |
          gh release delete ${{ env.RELEASE_VERSION }} --yes || true
          git push origin :refs/tags/${{ env.RELEASE_VERSION }} || true
          git tag -d ${{ env.RELEASE_VERSION }} || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create release notes
        run: |
          LATEST_TAG=${{ env.RELEASE_VERSION }}
          git tag $LATEST_TAG

          PREVIOUS_TAG=$(git describe --tags --abbrev=0 "${LATEST_TAG}^" 2>/dev/null || echo "")
          
          if [ -n "$PREVIOUS_TAG" ]; then
            echo "Full Changelog: https://github.com/${{ github.repository }}/compare/${PREVIOUS_TAG}...${LATEST_TAG}" > CHANGELOG.md
          else
            echo "Initial release" > CHANGELOG.md
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload binaries to a release
        uses: softprops/action-gh-release@v3
        with:
          body_path: CHANGELOG.md
          files: |
            artifacts/android/*
            artifacts/zygisk/*
            artifacts/windows/*
          tag_name: ${{ env.RELEASE_VERSION }}
